version: '3'

services:
  mqtt:
    image: "eclipse-mosquitto:1.4.12"
    ports:
      - 1883:1883
      - 9001:9001
  
  influx:
    image: "influxdb:1.6.1"
    volumes:
      - ./services/influx/data:/var/lib/influxdb
    ports:
      - 18086:8086